= Android Bootcamp Training

14 December 2015

*Marius Mailat*, +<marius.mailat@gmail.com>+
http://thewnewcircle.com[The New Circle, Inc.]

== Obtaining Course Materials

You can either clone this Git repository:

  git clone git://github.com/mailat/bootcamp-2015-12-14.git

or

   download a Zip archive by clicking the link at the top of the page or using the link: https://github.com/mailat/bootcamp-2015-12-14/zipball/master

== Useful Links

Git book: http://git-scm.com/book

Marakana Java Fundamentals Tutorial: http://marakana.com/bookshelf/java_fundamentals_tutorial/index.html

Introduction to Eclipse - Driving Java Productivity: http://mrkn.co/s/video_introduction_to_eclipse_driving_java_productivity,595/index.html

Java Tutorial http://docs.oracle.com/javase/tutorial/

Gradle NDK Experimental plugin transition - http://tools.android.com/tech-docs/new-build-system/gradle-experimental

Offical samples NDK - https://github.com/googlesamples/android-ndk

Xavier Hallade on NDK - http://www.youtube.com/watch?v=okLKfxfbz40

NDK Integration - http://ph0b.com/android-studio-gradle-and-ndk-integration/

Gradle NDK Experimental plugin - http://de.slideshare.net/ph0b/mastering-the-ndk-with-android-studio-and-the-gradleexperimental-plugin

== What should you start after finishing the training?

- Android Dev Summit coding labs 2015 - https://www.code-labs.io/android-dev-summit

== Homework Day 01

- Finish the lab activity in Labs_Bootcamp_Slides.html (Page 2)
- Have a Button which opens the Starwars cinema ticket
- Create a second activity names SecondActivity and start the second activity from StatusActivity.

== Homework Day 02

- Start/Finish the lab activity in Labs_Bootcamp_Slides.html (Page 27 - preferences)
- Create AsyncTask in StatusActivity (entry in the options menu "Manual refresh") and display the results in a TextView (optional in a ListView). Add optional a Spinner for the progress of the connection.
- Create a broadcast receiver for the Internet Connection ON, in case we receive internet we just START the RefreshService.class

== Homework Day 03

- Finish the lab activity in Labs_Bootcamp_Slides.html related to the Content Provider
- Create a Dialog in Android similar with the one from the link http://goo.gl/TMydaO. Use a new class AlertDialog extending the Dialog with a custom XML layout.
- Optional: Recreate the IntentService as a Service with a thread in it. Try to run it more than once.

== Homework Day 04

- Open the courseware_ndk/NewCircle_Android_Internals_Slides.html slides, press G and jump at the page 77. Follow the instruction to create the Android Studio project until the page 84.
- Additionaly to the please add the following elements too:

1. Make sure the JAVA_HOME, NDROID_HOME, ANDROID_NDK, GRADLE_HOME are setup correctly on your Enviroment Variables (Windows - Control panel; Mac - ~/.bash_profile )
2. /local.properties should contain your paths to SDK/NDK similar to:

	ndk.dir=/Users/mailat/Work/sdk/ndk-bundle
	sdk.dir=/Users/mailat/Work/sdk

3. In /gradle.properties please add the:

	android.useDeprecatedNdk=true

4. In /build.gradle please use

        classpath 'com.android.tools.build:gradle:1.3.1'
        or
        classpath 'com.android.tools.build:gradle:2.0.0-alpha2'

5. In /gradle/wrapper/gradle-wrapper.properties you should have:

	distributionUrl=https\://services.gradle.org/distributions/gradle-2.8-bin.zip

6. In the /app/build.gradle you should have something similar to:

apply plugin: 'com.android.application'

	android {
	    compileSdkVersion 23
	    buildToolsVersion "23.0.2"

	    defaultConfig {
	        applicationId "com.marakana.android.fibonaccinative"
	        minSdkVersion 17
	        targetSdkVersion 23
	        versionCode 1
	        versionName "1.0"

	        ndk {
	            moduleName "com_marakana_android_fibonaccinative_FibLib"
	            ldLibs "log"
	        }
	    }

	    buildTypes {
	        release {
	            minifyEnabled false
	            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
	        }
	        debug {
	            debuggable = true
	            jniDebuggable = true
	            ndk{
	                debuggable = true
	            }
	        }
	    }
	}







