= Android Bootcamp Training

14 December 2015

*Marius Mailat*, +<marius.mailat@gmail.com>+
http://thewnewcircle.com[The New Circle, Inc.]

== Obtaining Course Materials

You can either clone this Git repository:

  git clone git://github.com/mailat/bootcamp-2015-12-14.git

or

   download a Zip archive by clicking the link at the top of the page or using the link: https://github.com/mailat/bootcamp-2015-12-14/zipball/master

== Useful Links

Git book: http://git-scm.com/book

Marakana Java Fundamentals Tutorial: http://marakana.com/bookshelf/java_fundamentals_tutorial/index.html

Introduction to Eclipse - Driving Java Productivity: http://mrkn.co/s/video_introduction_to_eclipse_driving_java_productivity,595/index.html

Java Tutorial http://docs.oracle.com/javase/tutorial/

== What should you start after finishing the training?

- Android Dev Summit coding labs 2015 - https://www.code-labs.io/android-dev-summit

== Homework Day 01

- Finish the lab activity in Labs_Bootcamp_Slides.html (Page 2)
- Have a Button which opens the Starwars cinema ticket
- Create a second activity names SecondActivity and start the second activity from StatusActivity.

== Homework Day 02

- Start/Finish the lab activity in Labs_Bootcamp_Slides.html (Page 27 - preferences)
- Create AsyncTask in StatusActivity (entry in the options menu "Manual refresh") and display the results in a TextView (optional in a ListView). Add optional a Spinner for the progress of the connection.
- Create a broadcast receiver for the Internet Connection ON, in case we receive internet we just START the RefreshService.class

== Homework Day 03

- Finish the lab activity in Labs_Bootcamp_Slides.html related to the Content Provider
- Create a Dialog in Android similar with the one from the link http://goo.gl/TMydaO. Use a new class AlertDialog extending the Dialog with a custom XML layout.
- Optional: Recreate the IntentService as a Service with a thread in it. Try to run it more than once.
